apiVersion: v1
kind: Service
metadata:
  name: osrs-visualizer-service
  labels:
    app: osrs-visualizer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: osrs-visualizer
